/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://il53wzdhmjf2bpwu2idfk52fyi.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-ftpazb7crjhbvi57g7trcz7hey",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://xh5t44cqmj.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-west-2:156af593-1883-44e1-bd44-714eeaad9117",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_WVH60tdPQ",
    "aws_user_pools_web_client_id": "3m2umqqlaocpphgon529mmlquq",
    "oauth": {},
    "aws_user_files_s3_bucket": "wishlist-images202828-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
